
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  database: wallet_transactional_system
  username: postgres
  password: root

development:
  <<: *default

production:
  <<: *default
